# Generated by Django 5.2.1 on 2025-05-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=50, unique=True, verbose_name='Uçak Modeli Adı')),
            ],
            options={
                'verbose_name': 'Uçak Modeli',
                'verbose_name_plural': 'Uçak Modelleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=50, unique=True, verbose_name='Parça Tipi Adı')),
            ],
            options={
                'verbose_name': 'Parça Tipi',
                'verbose_name_plural': 'Parça Tipleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Seri Numarası')),
                ('status', models.CharField(choices=[('STOKTA', 'Stokta'), ('KULLANILDI', 'Kullanıldı'), ('GERI_DONUSUMDE', 'Geri Dönüşümde')], db_index=True, default='STOKTA', max_length=20, verbose_name='Durum')),
                ('aircraft_model_compatibility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatible_parts', to='envanter.aircraftmodel', verbose_name='Uyumlu Uçak Modeli')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
            },
        ),
    ]
