# Generated by Django 5.2.1 on 2025-05-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envanter', '0001_initial'),
        ('montaj', '0001_initial'),
        ('uretim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='produced_by_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_parts', to='uretim.team', verbose_name='Üreten Takım'),
        ),
        migrations.AddField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containing_assembly', to='montaj.assembledaircraft', verbose_name='Kullanıldığı Uçak'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envanter.parttype', verbose_name='Parça Tipi'),
        ),
    ]
